# Estudo sobre lançar exception TypeError em função no python

[⬆️ Voltar](https://github.com/Geofisicando/python-orientado-a-testes/tree/main#%C3%ADndice)

Neste exemplo, a função lança uma exception TypeError quando o tipo passado é diferente do esperado pela função.

Para rodar este exemplo basta utilizar o comando:

```
python3 main.py
```
